<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
   <dict>
      <key>fileTypes</key>
      <array>
         <string>html</string>
         <string>hpp</string>
         <string>config</string>
      </array>
      <key>name</key>
      <string>HTML++</string>
      <key>patterns</key>
      <array>
         <dict>
            <key>begin</key>
            <string>--\[</string>
            <key>end</key>
            <string>\]--</string>
            <key>name</key>
            <string>comment.block.documentation</string>
            <key>comment</key>
            <string>Dooble Comments</string>
         </dict>
         <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>text.html.pp.conditions</string>
            <key>patterns</key>
            <array>
               <dict>
                  <key>include</key>
                  <string>source.js</string>
               </dict>
            </array>
            <key>comment</key>
            <string>Dooble Loop</string>
         </dict>
         <dict>
            <key>match</key>
            <string>(@if|@else|@elseif|@endif|@loop|@endloop)</string>
            <key>name</key>
            <string>entity.other.inherited-class</string>
            <key>comment</key>
            <string>Dooble Saved Words Loops</string>
         </dict>
         <dict>
            <key>begin</key>
            <string>(\[\[)</string>
            <key>end</key>
            <string>(\]\])</string>
            <key>name</key>
            <string>text.html.pp.module</string>
            <key>comment</key>
            <string>Dooble Module Call</string>
            <key>patterns</key>
            <array>
               <dict>
                  <key>match</key>
                  <string>(?&lt;=\[|^$)\s*([^\s\]]+)\b</string>
                  <key>name</key>
                  <string>entity.name.tag</string>
               </dict>
               <dict>
                  <key>match</key>
                  <string>\s*([A-Za-z/]+)\b</string>
                  <key>name</key>
                  <string>entity.other.attribute-name</string>
               </dict>
               <dict>
                  <key>begin</key>
                  <string>(\')</string>
                  <key>end</key>
                  <string>(\')</string>
                  <key>name</key>
                  <string>string.quoted.single</string>
               </dict>
               <dict>
                  <key>begin</key>
                  <string>(\")</string>
                  <key>end</key>
                  <string>(\")</string>
                  <key>name</key>
                  <string>string.quoted.single</string>
               </dict>
            </array>
         </dict>
         <dict>
            <key>begin</key>
            <string>@{</string>
            <key>end</key>
            <string>}@</string>
            <key>name</key>
            <string>source.js.sjs</string>
            <key>comment</key>
            <string>Dooble SJS</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
         </dict>

         <dict>
            <key>include</key>
            <string>text.html.basic</string>
         </dict>

      </array>
      <key>scopeName</key>
      <string>text.html.pp</string>
      <key>uuid</key>
      <string>de8141c6-c6a3-4452-8a75-eb0f527dc043</string>
   </dict>
</plist>